server:
  port: 8013

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/courses_db
    #url: jdbc:postgresql://host.docker.internal:5432/courses_db
    #url: jdbc:postgresql://postgres:5432/courses_db
    username: ${POSTGRES_USER_LOGIN}
    password: ${POSTGRES_USER_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false # При open-in-view=false сессия Hibernate закрывается сразу после завершения транзакции в сервисном слое. (см заметки)
    show-sql: true

  liquibase:
    enabled: true
    change-log: 'classpath:db/changelog/course-service/db.changelog-master.yaml'

 
